# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  express:
    image: docker.io/bitnami/express:4
    ports:
      - '2222:22'
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/myapp
      - EXPRESS_SKIP_DB_WAIT=0
      - EXPRESS_SKIP_DB_MIGRATION=0
      - EXPRESS_SKIP_NPM_INSTALL=0
      - EXPRESS_SKIP_BOWER_INSTALL=0
      - EXPRESS_DEFAULT_MONGODB_DATABASE_PORT_NUMBER=27017
    volumes:
      - 'C:\Users\ignah\Desktop\NoWaste\my-project:/app'
    depends_on:
      - mongodb

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    volumes:
      - '.:/my-project'
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
